# Introducción

En el presente documento haremos el análisis de un conjunto de datos llamado "German Credit data" que contiene información categórica y numérica de personas que tienen un crédito bancario. El conjunto de datos fue obtendio de (Dua, D., & Graff, C., s.f.).

# Obtención de los datos

El primero paso es obtener los datos en un formato legible. El dataset original tiene la siguiente forma:

A11 6 A34 A43 1169 A65 A75 4 A93 A101 4 A121 67 A143 A152 2 A173 1 A192 A201 1
A12 48 A32 A43 5951 A61 A73 2 A92 A101 2 A121 22 A143 A152 1 A173 1 A191 A201 2
A14 12 A34 A46 2096 A61 A74 2 A93 A101 3 A121 49 A143 A152 1 A172 2 A191 A201 1
A11 42 A32 A42 7882 A61 A74 2 A93 A103 4 A122 45 A143 A153 1 A173 2 A191 A201 1
A11 24 A33 A40 4870 A61 A73 3 A93 A101 4 A124 53 A143 A153 2 A173 2 A191 A201 2
A14 36 A32 A46 9055 A65 A73 2 A93 A101 4 A124 35 A143 A153 1 A172 2 A192 A201 1
A14 24 A32 A42 2835 A63 A75 3 A93 A101 4 A122 53 A143 A152 1 A173 1 A191 A201 1
A12 36 A32 A41 6948 A61 A73 2 A93 A101 2 A123 35 A143 A151 1 A174 1 A192 A201 1
A14 12 A32 A43 3059 A64 A74 2 A91 A101 4 A121 61 A143 A152 1 A172 1 A191 A201 1
A12 30 A34 A40 5234 A61 A71 4 A94 A101 2 A123 28 A143 A152 2 A174 1 A191 A201 2
A12 12 A32 A40 1295 A61 A72 3 A92 A101 1 A123 25 A143 A151 1 A173 1 A191 A201 2
A11 48 A32 A49 4308 A61 A72 3 A92 A101 4 A122 24 A143 A151 1 A173 1 A191 A201 2
A12 12 A32 A43 1567 A61 A73 1 A92 A101 1 A123 22 A143 A152 1 A173 1 A192 A201 1
A11 24 A34 A40 1199 A61 A75 4 A93 A101 4 A123 60 A143 A152 2 A172 1 A191 A201 2
...

Como podemos notar es un formato ilegible, sin embargo, toma sentido cuando agregamos los nombres de las columnas y traducimos cada código en una descripción. Para hacer dicha traducción haremos uso del documento de llamado "german.doc" que contiene la información necesaria. El siguiente script de python nos ayudará a hacer la traducción de los códigos a columnas más descriptivas:

In [43]:
import pandas as pd

# Creamos un dataframe vacío
columnas=["Status of existing checking account",
         "Duration in month",
         "Credit history",
         "Purpose",
         "Credit amount",
         "Savings account/bonds",
         "Present employment since",
         "Installment rate in percentage of disposable income",
         "Personal status and sex",
         "Other debtors/guarantors",
         "Present residence since",
         "Property",
         "Age in years",
         "Other installment plans",
         "Housing",
         "Number of existing credits at this bank",
         "Job",
         "Number of people being liable to provide maintenance for",
         "Telephone",
         "Foreign worker",
         "Risk"]
df = pd.DataFrame(columns=columnas)

# Leemos el dataset
with open("dataset/german.data", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        renglon = linea.split(" ")
        renglon = [x.strip() for x in renglon]
        df_renglon = pd.DataFrame([renglon], columns=columnas)
        df = pd.concat([df, df_renglon])

# Definimos las reglas de traducción de códigos
df_1 = pd.DataFrame([["A11", "... < 0 DM"],
                    ["A12", "0 <= ... < 200 DM"],
                    ["A13", "... >= 200 DM/salary assignments for at least 1 year"],
                    ["A14", "no checking account"]],
                    columns=["Status of existing checking account","Valor"])
df_3 = pd.DataFrame([["A30","no credits taken/all credits paid back duly"],
                    ["A31","all credits at this bank paid back duly"],
                    ["A32","existing credits paid back duly till now"],
                    ["A33","delay in paying off in the past"],
                    ["A34", "critical account/other credits existing (not at this bank)"]],
                    columns=["Credit history","Valor"])
df_4 = pd.DataFrame([["A40", "car (new)"],
                    ["A41", "car (used)"],
                    ["A42", "furniture/equipment"],
                    ["A43", "radio/television"],
                    ["A44", "domestic appliances"],
                    ["A45", "repairs"],
                    ["A46", "education"],
                    ["A47", "(vacation - does not exist?)"],
                    ["A48", "retraining"],
                    ["A49", "business"],
                    ["A410", "others"]],
                    columns=["Purpose","Valor"]
                    )
df_6 = pd.DataFrame([["A61", "... < 100 DM"],
                    ["A62", "100 <= ... < 500 DM"],
                    ["A63", "500 <= ... < 1000 DM"],
                    ["A64", ".. >= 1000 DM"],
                    ["A65", "unknown/no savings account"]],
                   columns=["Savings account/bonds","Valor"])
df_7 = pd.DataFrame([["A71", "unemployed"],
                    ["A72", "... < 1 year"],
                    ["A73", "1 <= ... < 4 years"  ],
                    ["A74", "4 <= ... < 7 years"],
                    ["A75", "... >= 7 years"]],
                    columns=["Present employment since","Valor"])
df_9 = pd.DataFrame([["A91", "male: divorced/separated"],
                    ["A92", "female: divorced/separated/married"],
                    ["A93", "male: single"],
                    ["A94", "male: married/widowed"],
                    ["A95", "female: single"]],
                    columns=["Personal status and sex","Valor"])
df_10 = pd.DataFrame([["A101", "none"],
                    ["A102", "co-applicant"],
                    ["A103", "guarantor"]],
                    columns=["Other debtors/guarantors","Valor"])
df_12 = pd.DataFrame([["A121", "real estate"],
                    ["A122", "building society savings agreement/life insurance"],
                    ["A123", "car or other, not in attribute 6"],
                    ["A124", "unknown/no property"]],
                    columns=["Property","Valor"])
df_14 = pd.DataFrame([["A141", "bank"],
                    ["A142", "stores"],
                    ["A143", "none"]],
                    columns=["Other installment plans","Valor"])
df_15 = pd.DataFrame([["A151", "rent"],
                    ["A152", "own"],
                    ["A153", "for free"]],
                    columns=["Housing","Valor"])
df_17 = pd.DataFrame([["A171", "unemployed/ unskilled - non-resident"],
                    ["A172", "unskilled - resident"],
                    ["A173", "skilled employee/official"],
                    ["A174", "management/self-employed/highly qualified employee/officer"]],
                    columns=["Job","Valor"])
df_19 = pd.DataFrame([["A191", "none"],
                    ["A192", "yes, registered under the customers name"]],
                    columns=["Telephone","Valor"])
df_20 = pd.DataFrame([["A201", "yes"],
                    ["A202", "no"]],
                    columns=["Foreign worker","Valor"])
df_21 = pd.DataFrame([["1", "Good"],
                    ["2", "Bad"]],
                    columns=["Risk","Valor"])

# Traducimos los códigos del daframe original con ayuda de los catálogos anteriores
lista_df = [df_1, df_3, df_4, df_6, df_7, df_9, df_10, df_12, df_14, df_15, df_17, df_19, df_20, df_21]
for df_i in lista_df:
    nombreColumna = df_i.columns[0]
    df = pd.merge(df, df_i, on=nombreColumna, how="left")
    df.drop(columns = nombreColumna, inplace = True)
    df.rename(columns={"Valor":nombreColumna}, inplace = True)

# Reordenamos las columnas como estaban originalmente
df = df[columnas]

#Mostramos el resultado final
df.head()

,Status of existing checking account,Duration in month,Credit history,Purpose,Credit amount,Savings account/bonds,Present employment since,Installment rate in percentage of disposable income,Personal status and sex,Other debtors/guarantors,...,Property,Age in years,Other installment plans,Housing,Number of existing credits at this bank,Job,Number of people being liable to provide maintenance for,Telephone,Foreign worker,Risk
0,... < 0 DM,6,critical account/other credits existing (not a...,radio/television,1169,unknown/no savings account,... >= 7 years,4,male: single,none,...,real estate,67,none,own,2,skilled employee/official,1,"yes, registered under the customers name",yes,Good
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,radio/television,5951,... < 100 DM,1 <= ... < 4 years,2,female: divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,none,yes,Bad
2,no checking account,12,critical account/other credits existing (not a...,education,2096,... < 100 DM,4 <= ... < 7 years,2,male: single,none,...,real estate,49,none,own,1,unskilled - resident,2,none,yes,Good
3,... < 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,... < 100 DM,4 <= ... < 7 years,2,male: single,guarantor,...,building society savings agreement/life insurance,45,none,for free,1,skilled employee/official,2,none,yes,Good
4,... < 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male: single,none,...,unknown/no property,53,none,for free,2,skilled employee/official,2,none,yes,Bad

# Limpieza y transformación de datos
Como podemos notar en los catálogos anteriores, tanto en el nombre de las columnas como en la descripción de cada código se respetó tanto como fue posible los nombres originales que aparecen en el documento "german.doc". Ahora es momento de corregir los tipos de datos, revisar si tenemos valores nulos o duplicados:

In [51]:
# Convertimos las columnas numéricas a tipo entero
df = df.astype({'Duration in month': 'int',
                'Credit amount': 'int',
                'Installment rate in percentage of disposable income': 'int',
                'Present residence since': 'int',
                'Age in years': 'int',
                'Number of existing credits at this bank': 'int',
                'Number of people being liable to provide maintenance for': 'int'})

# Imprimimos el esquema de los datos
print(df.info())

# Validamos las columnas con valores nulos
print(df.isna().sum())

# Validamos si existen renglones duplicados
print(f"Número de duplicados: {df.duplicated().sum()}")

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Status of existing checking account                       1000 non-null   str
 1   Duration in month                                         1000 non-null   int64
 2   Credit history                                            1000 non-null   str
 3   Purpose                                                   1000 non-null   str
 4   Credit amount                                             1000 non-null   int64
 5   Savings account/bonds                                     1000 non-null   str
 6   Present employment since                                  1000 non-null   str
 7   Installment rate in percentage of disposable income       1000 non-null   int64
 8   Personal status and sex                                   1000 non-null   str
 9   Other debtors/guarantors                                  1000 non-null   str
 10  Present residence since                                   1000 non-null   int64
 11  Property                                                  1000 non-null   str
 12  Age in years                                              1000 non-null   int64
 13  Other installment plans                                   1000 non-null   str
 14  Housing                                                   1000 non-null   str
 15  Number of existing credits at this bank                   1000 non-null   int64
 16  Job                                                       1000 non-null   str
 17  Number of people being liable to provide maintenance for  1000 non-null   int64
 18  Telephone                                                 1000 non-null   str
 19  Foreign worker                                            1000 non-null   str
 20  Risk                                                      1000 non-null   str
dtypes: int64(7), str(14)
memory usage: 164.2 KB
None
Status of existing checking account                         0
Duration in month                                           0
Credit history                                              0
Purpose                                                     0
Credit amount                                               0
Savings account/bonds                                       0
Present employment since                                    0
Installment rate in percentage of disposable income         0
Personal status and sex                                     0
Other debtors/guarantors                                    0
Present residence since                                     0
Property                                                    0
Age in years                                                0
Other installment plans                                     0
Housing                                                     0
Number of existing credits at this bank                     0
Job                                                         0
Number of people being liable to provide maintenance for    0
Telephone                                                   0
Foreign worker                                              0
Risk                                                        0
dtype: int64
Número de duplicados: 0

Como podemos notar en los resultados anteriores, los tipos de datos son correctos, no existen valores nulos y no existen rengloes duplicados. Ahora vamos a aplicar una transformación a la columna "Personal status and sex" ya que nos interesa tener el estatus personal y el género de la persona en dos columnas separadas. El código es el siguiente:

In [54]:
df[["Personal status","Sex"]] = df["Personal status and sex"].str.split(':', expand=True)
df["Personal status"] = df["Personal status"].str.strip()
df["Sex"] = df["Sex"].str.strip()
df[["Personal status","Sex"]].head()

  Personal status                         Sex
0            male                      single
1          female  divorced/separated/married
2            male                      single
3            male                      single
4            male                      single

# Referencias
Dua, D., & Graff, C. (s.f.). Statlog (German credit data) [Conjunto de datos]. UCI Machine Learning Repository. Recuperado el 10 de agosto de 2026, de https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data